### ISSUE TITLE
How to use with vagrant box

### ISSUE THREAD

**Issue by frob** [hechoendrupal/DrupalConsole#1241]
How would I use this with a vagrant box. I am using the popular drupal-vm development vagrant environment. If I am in the shared drupal directory locally I get this error:

```
[PDOException]                                                                              
  SQLSTATE[HY000] [1045] Access denied for user 'drupalvm'@'localhost' (using password: YES)
```

However, if I am in a non-drupal directory then drupal console will allow me to generate things.

Will I have to log into the vagrant box and install drupal console to run commands there?

**Comment by jmolivas** [comment]
@frob: You can take advantage of Drupal Console remote command execution feature, I will try to write some docs during the weekend in the meantime this is an overview about the steps.

* Execute `drupal init` to copy configuration files 
![drupal-init](https://cloud.githubusercontent.com/assets/366275/11161449/96cdaf8a-8a31-11e5-9f4f-2e8e56f496a9.png)

* Edit global configuration related to remote connection at copied file `~/.console/config.yml`
```
application:
...
  remote:
    user: root
    port: 22
    console: /usr/local/bin/drupal
    options: --ansi
    arguments:
    keys:
      public: ~/.ssh/id_rsa.pub
      private: ~/.ssh/id_rsa
      passphrase: ~/.ssh/passphrase.txt
```
* Duplicate specific remote site configuration from `~/.console/sites/sample.yml `
```
local:
  root: /var/www/drupal8.dev
  host: local
dev:
  root: /var/www/html/drupal
  host: 140.211.10.62
  user: drupal
prod:
  root: /var/www/html/docroot
  host: live.drupal.org
  user: drupal
  console: /var/www/html/docroot/console.phar
```
* Execute `site:debug` to debug configured sites:
![console-site-debug-1](https://cloud.githubusercontent.com/assets/366275/11161480/c87746e4-8a32-11e5-8fdc-722a1e6d23aa.png)

* Execute `site:debug SITE_NAME` to debug site configuration details:
![console-site-debug-2](https://cloud.githubusercontent.com/assets/366275/11161482/e0abe3b4-8a32-11e5-929e-d3b6d4cc4efc.png)

* Execute `drupal --target=SITE_NAME cr all`
![console-drupal-target](https://cloud.githubusercontent.com/assets/366275/11161497/1fd2a668-8a33-11e5-898a-19331a98d58c.png)

##### NOTE: DrupalVM provides Drupal Console (if using Drupal 8+), when ssh into the VM
