### ISSUE TITLE
[generate:breakpoints] Command to generate breakpoints

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1373]
## Problem/Motivation
Drupal 8 comes with breakpoints module in core. We should add the ability of generating breakpoints with a command.

## Solution
We should provide a `generate:breakpoints` that this will generate the yml file with the following structure.

````
bartik.mobile:
  label: mobile
  mediaQuery: '(min-width: 0px)'
  weight: 0
  multipliers:
    - 1x
bartik.narrow:
  label: narrow
  mediaQuery: 'all and (min-width: 560px) and (max-width: 850px)'
  weight: 1
  multipliers:
    - 1x
bartik.wide:
  label: wide
  mediaQuery: 'all and (min-width: 851px)'
  weight: 2
  multipliers:
    - 1x
`````

Here is more information about breakpoints in D8  [Working with breakpoints in Drupal 8](https://www.drupal.org/documentation/modules/breakpoint)
