### ISSUE TITLE
Generate menu links

### ISSUE THREAD

**Issue by willwh** [hechoendrupal/DrupalConsole#1385]
Create module_name.menu.links.yml as part of generate:form:config to create a menu link.

It would be nice if the default was something like the following:

**module_name.menu.links.yml**
```
module_name.default_form:
  title: 'Default Form'
  description: ''
  parent: system.admin_config_development
  route_name: module_name.default_form
```
