### ISSUE TITLE
[generate:entity:content] Admin menu doesn't display listing entry

### ISSUE THREAD

**Issue by smalot** [hechoendrupal/DrupalConsole#1389]
On the admin index homepage (http://localhost/admin/index) we correctly see links to : 
- setup permissions
- handle fields

But the link to list all entities or to add a new one is not displayed.
In the module.links.menu.yml I made this quick fix, by adding the "parent" entry : 

````yaml
# Animation menu items definition
entity.animation.collection:
  title: 'Animation list'
  route_name: entity.animation.collection
  description: 'List Animation entities'
  parent: system.admin_content
````

I should be interesting too to see a tab in the "admin/content" with the name of entity type created.

I think it's not the better way, but the need is real  ;-)

Many thanks for your help

**Comment by smalot** [comment]
In the `module.links.task.yml` I have added those lines : 

````yaml
animation.content:
  route_name: entity.animation.collection
  title: 'Animation list'
  base_route: system.admin_content
````
