### ISSUE TITLE
[console] Learning mode: New global option in config file

### ISSUE THREAD

**Issue by develCuy** [hechoendrupal/DrupalConsole#1729]
As a newbie to Drupal 8, I would like to have --learning param set for every single command, so no need to type it all the time.

**Comment by jmolivas** [comment]
:+1: What I love about this one is once this is fixed any global option could be set using the config file.

**Comment by darol100** [comment]
This seem to be fixed... ( base on the tag) I'm closing this issue feel free to reopened if not fixed.

**Comment by darol100** [comment]
Reopening this because this have not been merge to master... mine mistake.

**Comment by develCuy** [comment]
Let the party begin!

**Comment by jmolivas** [comment]
Merged @develCuy  thanks for this idea ;)

**Comment by jmolivas** [comment]
@develCuy @darol100 This change is on the latest v0.10.5 release.

To take advantage of default global options, execute `drupal init --override` first, then do the override on your home directory config file `~/.console/config.yml` 

If you do not want to override the file, you can copy and paste the new keys:
```
    global:
      options:
        learning: true
        # generate-inline: true
        # generate-chain: true
        # yes: true
```
