### ISSUE TITLE
[chain] Allow command to have placeholders

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#2055]
### Problem / Motivation
We are duplicating chain scripts because minor configuration changes. If you allow chain commands to actually get a question and use them as placeholder later into our scripts this will eliminate duplication of chains.

Here are two example of Duplication of chains: 
- Casper project - https://www.drupal.org/node/2668516
- Quick Start - https://github.com/hechoendrupal/DrupalConsole/issues/1990

### Solution:
- Add the ability to provide `name`, `question`, `options` into Chains commands.

**Comment by jmolivas** [comment]
Based on how the current configuration for commands is handled, we can do something like this:

* Discovering YAML file as command:
```
command:
  name: casper:config
  description: Import casper Manage Form and Manage Display configuration.
```
* Options definition:
```
  options:
    theme-path: Theme path
  defaults:
    theme-path: themes/casper
  questions:
    theme-path:  Enter theme path
```
* Option keys seems kinda duplicated, we can probably propose a better structure:
```
  options:
    theme-path:
      name: Theme path
      default: themes/casper
      question: Enter theme path
```

**Comment by jmolivas** [comment]
I am still not yet convinced about registering chain files as Command (sounds like black magic to me)

But I was playing with some code to support placeholders and I got something working. 

I believe we can have different types of placeholders.

### Inline placeholders:
* Definition:
```
  - command: site:install
    options:
      langcode: en
      db-type: mysql
      db-host: 127.0.0.1
      db-name: %db-name% 
      db-user: %db-user%
      db-pass: %db-pass%
```
* Usage passing using the `--placeholders` option:
```
drupal chain file=/path/to/chain.yml --placeholders="db-name:drupal db-user:root db-pass:root"
```

### Environment placeholders:
* Definition:
```
  - command: site:install
    options:
      langcode: en
      db-type: mysql
      db-host: 127.0.0.1
      db-name: getenv(DATABASE_NAME)
      db-user: getenv(DATABASE_USER)
      db-pass: getenv(DATABASE_PASSWORD)
```
* Usage defining env variables
```
export export DATABASE_NAME=drupal
export export DATABASE_USER=root
export export DATABASE_PASSWORD=root

drupal chain file=/path/to/chain.yml 
```

**Comment by LightGuard** [comment]
I like it, but wouldn't it be better to have all interpolations happen
based on a delimiter?

    someKey: %getenv(VARIABLE)%

That way it's consistent, and less chance of magic looking things :)

On Thursday, April 14, 2016, Jesus Manuel Olivas <notifications@github.com>
wrote:

> @dabito <https://github.com/dabito> @igasi <https://github.com/igasi>
> @LightGuard <https://github.com/LightGuard>
>
> I was playing with de idea to support placeholders and I got some working
> code.
>
> I believe we can have different types of placeholders.
> Inline placeholders:
>
>    - Definition:
>
>   - command: site:install
>     options:
>       langcode: en
>       db-type: mysql
>       db-host: 127.0.0.1
>       db-name: %db-name%
>       db-user: %db-user%
>       db-pass: %db-pass%
>
>
>    - Usage passing using the --placeholders option:
>
> drupal chain file=/path/to/chain.yml --placeholders="db-name:drupal db-user:root db-pass:root"
>
> Environment placeholders:
>
>    - Definition:
>
>   - command: site:install
>     options:
>       langcode: en
>       db-type: mysql
>       db-host: 127.0.0.1
>       db-name: getenv(DATABASE_NAME)
>       db-user: getenv(DATABASE_USER)
>       db-pass: getenv(DATABASE_PASSWORD)
>
>
>    - Usage defining env variables
>
> export export DATABASE_NAME=drupal
> export export DATABASE_USER=root
> export export DATABASE_PASSWORD=root
>
> drupal chain file=/path/to/chain.yml
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hechoendrupal/DrupalConsole/issues/2055#issuecomment-210212670>
>


-- 
Sent from Gmail Mobile

**Comment by dabito** [comment]
I see where @LightGuard is going... perhaps just use the placeholder and have it check if it's not defined by --placeholder, then check getenv? that way you could have simply %VARIABLE%

**Comment by LightGuard** [comment]
I actually like that idea better

On Thursday, April 14, 2016, David Gil <notifications@github.com> wrote:

> I see where @LightGuard <https://github.com/LightGuard> is going...
> perhaps just use the placeholder and have it check if it's not defined by
> --placeholder, then check getenv? that way you could have simply %VARIABLE%
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hechoendrupal/DrupalConsole/issues/2055#issuecomment-210259668>
>


-- 
Sent from Gmail Mobile

**Comment by igasi** [comment]
Maybe, we can simplify only use capital letters for env vars, and passing as option --env for identify.

```
# Definition chain file
  - command: site:install
    options:
      langcode: en
      db-type: mysql
      db-host: 127.0.0.1
      db-name: %DATABASE_NAME%
      db-user: %DATABASE_USER%
      db-pass: %DATABASE_PASSWORD%

# Usage
export export DATABASE_NAME=drupal
export export DATABASE_USER=root
export export DATABASE_PASSWORD=root

drupal chain file=/path/to/chain.yml --env
```

**Comment by jmolivas** [comment]
@LightGuard like the idea of adding a delimiter for environment placeholders.

@dabito but we need to properly identify between them.

@igasi how about when you need to pass both `--placeholders="key1:value1 key2:value2"` but also want to read some `--env` values.

We can probably use a different delimiter to easily identify inline placeholders and environment placeholders:
```
# Definition chain file
  - command: site:install
    options:
      langcode: en
      db-type: mysql
      db-host: 127.0.0.1
      db-name: [DATABASE_NAME]
      db-user: (DATABASE_USER)
      db-pass: ${DATABASE_PASSWORD}
```

We just need to pick one

**Comment by LightGuard** [comment]
I'd suggest sticking to one delimiter, but forcing the user to specify
inline or env, or maybe both with inline trumping env. ${}, #{}, $(),
and {{}} are all often seen in various templating and scripting languages.
Any of those seem like a good choice and less likely to be actual values
people might use for valid values.

Also, what happens if no valid value is found, error, NULL or empty string?

On Thursday, April 14, 2016, Jesus Manuel Olivas <notifications@github.com>
wrote:

> @LightGuard <https://github.com/LightGuard> like the idea of adding a
> delimiter for environment placeholders.
>
> @dabito <https://github.com/dabito> but we need to properly identify
> between them.
>
> @igasi <https://github.com/igasi> how about when you need to pass both --placeholders="key1:value1
> key2:value2" but also want to read some --env values.
>
> We can probably use a different delimiter to easily identify inline
> placeholders and environment placeholders:
>
> # Definition chain file
>   - command: site:install
>     options:
>       langcode: en
>       db-type: mysql
>       db-host: 127.0.0.1
>       db-name: [DATABASE_NAME]
>       db-user: (DATABASE_USER)
>       db-pass: ${DATABASE_PASSWORD}
>
> We just need to pick one
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hechoendrupal/DrupalConsole/issues/2055#issuecomment-210269919>
>


-- 
Sent from Gmail Mobile

**Comment by jmolivas** [comment]
How about using something like this:

| Type | Delimiter |
| --- | --- |
| Inline | {placeholder} |
| Env | ${placeholder} |

**Comment by LightGuard** [comment]
As long as your pretty sure those are characters (`{`, `}`, `$`) that wouldn't normally be valid in the document, sure. Or you'd need some way of allowing them to be escaped.

**Comment by jmolivas** [comment]
@LightGuard you are right, in order to avoid conflicts with route path definitions on chain.yml files we may need to change the delimiter to something else

| Type | Delimiter |
| --- | --- |
| Inline | {{placeholder}} |
| Env | ${{placeholder}} |

**Comment by jmolivas** [comment]
I wrote some code and this is how the command works:

### Command execution:
Using `--placeholder` to pass placeholder values no interaction is triggered.
```
drupal chain 
--file=/Users/jmolivas/.console/chain/update-gitbook-local.yml 
--placeholder="book_path:/Users/jmolivas/develop/drupal/docs/drupal-console-book"
```

### Error when placeholder is missing.
When the `-n` option is used to avoid interaction and the `--placeholder` option is not passed for the required placeholder(s) the command will thrown an error
![chain-error](https://cloud.githubusercontent.com/assets/366275/14584789/58b310c6-040e-11e6-903d-f6f618be7fc5.png)

### Interactive execution.
When using the interactive mode the command detects the missing inline placeholders and ask for the values
![chain-interactive](https://cloud.githubusercontent.com/assets/366275/14584818/d0322416-040e-11e6-8cb4-51dfb0c8ad1c.png)

### Content of the used YAML file on this example
```
commands:
  - command: settings:set
    arguments:
        setting-name: language
        setting-value: en
  - command: generate:doc:gitbook
    options:
        path: '{{book_path}}/en'
  - command: settings:set
    arguments:
        setting-name: language
        setting-value: es
  - command: generate:doc:gitbook
    options:
        path: '{{book_path}}/es'
  - command: settings:set
    arguments:
        setting-name: language
        setting-value: hi
  - command: generate:doc:gitbook
    options:
        path: '{{book_path}}/hi'
  - command: settings:set
    arguments:
        setting-name: language
        setting-value: hu
  - command: generate:doc:gitbook
    options:
        path: '{{book_path}}/hu'
  - command: settings:set
    arguments:
        setting-name: language
        setting-value: pt_br
  - command: generate:doc:gitbook
    options:
        path: '{{book_path}}/pt_br'
  - command: settings:set
    arguments:
        setting-name: language
        setting-value: ro
  - command: generate:doc:gitbook
    options:
        path: '{{book_path}}/ro'
  - command: settings:set
    arguments:
        setting-name: language
        setting-value: vn
  - command: generate:doc:gitbook
    options:
        path: '{{book_path}}/vn'
  - command: settings:set
    arguments:
        setting-name: language
        setting-value: zh_hans
  - command: generate:doc:gitbook
    options:
        path: '{{book_path}}/zh_hans'
  - command: settings:set
    arguments:
        setting-name: language
        setting-value: en
```

**Comment by jmolivas** [comment]
## Environment placeholders
### Command execution:
Execute `chain` command as usual
```
drupal chain --file=/Users/jmolivas/.console/chain/quick-start-db-env.yml
```

### Error when missing environment placeholder .
![chain-env-error](https://cloud.githubusercontent.com/assets/366275/14589381/a2575656-0495-11e6-9f10-f8dc10e751c1.png)

### Content of the used YAML file on this example
```
commands:
# Download Drupal
  - command: site:new
    arguments:
      directory: drupal8.dev
      version: 8.0.6
# Install Drupal
  - command: site:install
    options:
      langcode: en
      db-type: '${{DATABASE_TYPE}}'
      db-host: '${{DATABASE_HOST}}'
      db-name: '${{DATABASE_NAME}}'
      db-user: '${{DATABASE_USER}}'
      db-pass: '${{DATABASE_PASSWORD}}'
      db-port: '${{DATABASE_PORT}}'
      site-name: 'Drupal 8 site'
      site-mail: admin@example.org # default email
      account-name: admin # default account
      account-mail: admin@example.org # default email
      account-pass: admin # default pass
    arguments:
      profile: standard
# Start php built-in server
  - command: server
```

**Comment by igasi** [comment]
It looks great, much simpler.

The command chain
- With inline placeholder are defined varibales between '{{var}}' in the yml file to run it you need to add the --placeholders = option "key: var" separated by space.
- With environment variables are defined as '$ {{var}}' in the yml file, environment variables must be defined in the system, and only need to call yml file to recognize them.

**Comment by jmolivas** [comment]
After running some test with @igasi, we find out to avoid any conflicts, between inline & environment palcehoders, and easily support more placeholder types to standardize them.

We propose to add an identifier prefix character to each placeholder type.

| Type | Delimiter |
| --- | --- |
| Inline | %{{placeholder}} |
| Environment | ${{placeholder}} |
| Other | @{{placeholder}} |
| Another | #{{placeholder}} |

>NOTE: Placeholder names does not support `-` character, must use `_` instead.

### YAML file containing inline placeholders
```
commands:
# Download Drupal
  - command: site:new
    arguments:
      directory: drupal8.dev
      version: 8.0.6
# Install Drupal
  - command: site:install
    options:
      langcode: en
      db-type: '%{{db_type}}'
      db-host: '%{{db_host}}'
      db-name: '%{{db_name}}'
      db-user: '%{{db_user}}'
      db-pass: '%{{db_pass}}'
      db-port: '%{{db_port}}'
      site-name: 'Drupal 8 site'
      site-mail: admin@example.org # default email
      account-name: admin # default account
      account-mail: admin@example.org # default email
      account-pass: admin # default pass
    arguments:
      profile: standard
# Start php built-in server
  - command: server
```

### YAML file containing environment placeholders
```
commands:
# Download Drupal
  - command: site:new
    arguments:
      directory: drupal8.dev
      version: 8.0.6
# Install Drupal
  - command: site:install
    options:
      langcode: en
      db-type: '${{DATABASE_TYPE}}'
      db-host: '${{DATABASE_HOST}}'
      db-name: '${{DATABASE_NAME}}'
      db-user: '${{DATABASE_USER}}'
      db-pass: '${{DATABASE_PASSWORD}}'
      db-port: '${{DATABASE_PORT}}'
      site-name: 'Drupal 8 site'
      site-mail: admin@example.org # default email
      account-name: admin # default account
      account-mail: admin@example.org # default email
      account-pass: admin # default pass
    arguments:
      profile: standard
# Start php built-in server
  - command: server
```

**Comment by jmolivas** [comment]
@igasi and I keep playing with the inline placeholder feature and add default values to the placeholder definition:

### YAML file containing inline placeholders with defaults
```
commands:
# Download Drupal
  - command: site:new
    arguments:
      directory: drupal8.dev
      version: 8.0.6
# Install Drupal
  - command: site:install
    options:
      langcode: en
      db-type: '%{{db_type|mysql}}'
      db-host: '%{{db_host|127.0.0.1}}'
      db-name: '%{{db_name|drupal}}'
      db-user: '%{{db_user|root}}'
      db-pass: '%{{db_pass}}'
      db-port: '%{{db_port|3306}}'
      site-name: 'Drupal 8 site'
      site-mail: admin@example.org # default email
      account-name: admin # default account
      account-mail: admin@example.org # default email
      account-pass: admin # default pass
    arguments:
      profile: standard
# Start php built-in server
  - command: server
```

This is how the execution looks like:
![chain-inline-defaults](https://cloud.githubusercontent.com/assets/366275/14591074/29ec2c94-04bf-11e6-8f4d-9fe3e7caed8f.png)

**Comment by LightGuard** [comment]
+1 for the syntax. -1 for defaults.

If you need something for the chain to run, specify it. It's too easy to
put a default in and forget it's in there then things go wrong during a
critical build but it doesn't fail and the wrong thing is pushed, seen it
too many times. Or you end up committing the file with sensitive data in
for the default.

On Sunday, April 17, 2016, Jesus Manuel Olivas <notifications@github.com>
wrote:

> @igasi <https://github.com/igasi> and I keep playing with the inline
> placeholder feature and add default values to the placeholder definition:
> YAML file containing inline placeholders with defaults
>
> commands:
> # Download Drupal
>   - command: site:new
>     arguments:
>       directory: drupal8.dev
>       version: 8.0.6
> # Install Drupal
>   - command: site:install
>     options:
>       langcode: en
>       db-type: '%{{db_type|mysql}}'
>       db-host: '%{{db_host|127.0.0.1}}'
>       db-name: '%{{db_name|drupal}}'
>       db-user: '%{{db_user|root}}'
>       db-pass: '%{{db_pass}}'
>       db-port: '%{{db_port|3306}}'
>       site-name: 'Drupal 8 site'
>       site-mail: admin@example.org <javascript:_e(%7B%7D,'cvml','admin@example.org');> # default email
>       account-name: admin # default account
>       account-mail: admin@example.org <javascript:_e(%7B%7D,'cvml','admin@example.org');> # default email
>       account-pass: admin # default pass
>     arguments:
>       profile: standard
> # Start php built-in server
>   - command: server
>
> This is how the execution looks like:
> [image: chain-inline-defaults]
> <https://cloud.githubusercontent.com/assets/366275/14591074/29ec2c94-04bf-11e6-8f4d-9fe3e7caed8f.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hechoendrupal/DrupalConsole/issues/2055#issuecomment-211136641>
>


-- 
Sent from Gmail Mobile

**Comment by jmolivas** [comment]
@LightGuard I understand your concern about the default values, but those are not required. You can set default or leave  the placeholder without it.

As clarification at this, only inline placeholders accept a default value, environment placeholders does not and we do not have plans to support them at this point.

We can probably add a note, to the docs explaining the risk, and update our example and remove the default value on `db_user` placeholder.
```
commands:
# Download Drupal
  - command: site:new
    arguments:
      directory: drupal8.dev
      version: 8.0.6
# Install Drupal
  - command: site:install
    options:
      langcode: en
      db-type: '%{{db_type|mysql}}'
      db-host: '%{{db_host|127.0.0.1}}'
      db-name: '%{{db_name|drupal}}'
      db-user: '%{{db_user}}'
      db-pass: '%{{db_pass}}'
      db-port: '%{{db_port|3306}}'
      site-name: 'Drupal 8 site'
      site-mail: admin@example.org # default email
      account-name: admin # default account
      account-mail: admin@example.org # default email
      account-pass: admin # default pass
    arguments:
      profile: standard
# Start php built-in server
  - command: server
```
