### ISSUE TITLE
[module:uninstall] trying to reinstall module in a chain file, module:uninstall/install fails

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/DrupalConsole#2265]
i have the following chain file
```
commands:
  - command: module:uninstall
    arguments:
      module:
        - '%{{module}}'
    options:
      verbose
  - command: module:install
    arguments:
      module:
        - '%{{module}}'
    options:
      verbose
```

i execute it with the following command:
```drupal chain --file="~/.console/chain/reinstall.yml" --placeholder="module:chosen"```

my idea is to uninstall & then install a given module.
strangely, it works if i do the operations manually, but it fails when using the chain file, as seen in the following screenshot:

![seleccion_571](https://cloud.githubusercontent.com/assets/423279/15290610/eca22b64-1b79-11e6-8e58-5a7886b96a84.png)

is the placeholder in .yml file wrong?

**Comment by novia713** [comment]
well, finally got it working.
![seleccion_574](https://cloud.githubusercontent.com/assets/423279/15299033/cd6e56ea-1ba2-11e6-8422-a5c228c96913.png)


seems «uninstall« expects a string and «install» expects an array.

**i firmly suggest «uninstall» should accept an array**

i leave here my chain file for other people interested on this.

```
commands:
  - command: module:uninstall
    arguments:
      module: '%{{module}}'
    options:
      verbose
  - command: module:install
    arguments:
      module:
      - '%{{module}}'
    options:
      verbose
```
