### ISSUE TITLE
[placeholder] For module, theme and profile path

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#2267]
### Problem / Motivation
A very common use case of the Placeholder is having the ability of finding the location of a theme / module or a profile.

### Solution
Provide the ability of having this as placeholder and it should provide you the location of the project. 

The syntax should be similar to this:

- `@{{theme_path('casper')}}` 
- `@{{tprofile_path('pathauto')}}`
- `@{{module_path('thunder')}}`

**Comment by jmolivas** [comment]
Another option is to:

* Execute php funcitons
  `@{{drupal_get_path('theme','casper')}}`

* Call a method within a service
  `@{{service_name.method(agr1, agr2)}}`

**Comment by novia713** [comment]
just a bit offtopic, but i would like to say i don't feel intuitive nor like the syntax for placeholders here.
i don't like %{{ }} nor @{{ }}

why can't it be something more simple?

**Comment by jmolivas** [comment]
@novia713 we needed to add a key that is not possible to be present on the YAML definition.

**Comment by jmolivas** [comment]
I like to make sure we do not get confused with service having `.` on the name:

- instead of this:
`@{{service_name.method('agr1', 'agr2', 'agr3')}}`

- we could implement somehitng like this:
 -  `@{{service_name->method('agr1', 'agr2', 'agr3')}}`
 -  `@{{service('service_name').method('agr1', 'agr2', 'agr3')}}`

**Comment by marcelovani** [comment]
I have another use for this
I have a chain to build a site, which will:

- Checkout the repo (parameters: site-name, branch, destination-directory)
- Run composer install (parameters: destination-directory)

I would like to use a function to pull the repo url and the available branches when I enter the site name.
i.e.
```
vars:
  siteName: @{{name}}
commands:
# Checkout site using site name passed as parameter
  - command: exec
    arguments:
      # Ask backend for the repo url and branch.  The details will come from the yml file for the site name passed as parameter
      bin: 'git clone @{{getSiteRepo(siteName)} --branch @{{getBranches(siteName)}} %{{dir}}'
  - command: exec
    arguments:
      bin: 'cd %{{dir}}; composer install'
```
