### ISSUE TITLE
[console] Adding a tip in each command execution

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/DrupalConsole#2303]
i know this is an audacious idea, but what if we show a tip in each execution command?
i think this could improve the level of knowledge about the tool for users easily.

these tips could be related with the actual command or not. i should let this configurable.

initially, i would put a variable in config.yml like
`tips: true`

an example of a random tip would be →
![seleccion_598](https://cloud.githubusercontent.com/assets/423279/15422409/c427a068-1e78-11e6-8f6d-932c3b34f633.png)

we can collect tips in a .csv file, even let the community contribute them

**Comment by enzolutions** [comment]
I love the idea, could you propose a PR?

**Comment by jmolivas** [comment]
👍 for this idea:

This tips can be:
* Displayed if `--learning` option is turned on the configuration file. 
* Maintained on the translation files to take advantage of this feature.
* Added to the gitbook and http://drupalconsole.com/commands/
* Added to the help page.

**Comment by jmolivas** [comment]
We can automate adding to gitbook as the examples on the configuration files:
https://github.com/hechoendrupal/DrupalConsole/blob/master/config/translations/en/config.override.yml

```
description: 'Override config value in active configuration.'
...
examples:
    - description: 'Set the Contact module flood limit to 10.'
      execution: 'drupal config:override contact.settings flood.limit 10'
```

![](https://monosnap.com/file/VByYrAt2uHvKBkCAbALjsTrHW2QRtQ.png)
