### ISSUE TITLE
[console] Improve structure of translation files

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#2308]
## Problem / Motivation
Improve the structure of translation files to make less redundant and easy to scale. 

## Solution
* Current options definition:
```
  options:
    theme-path: Theme path
  defaults:
    theme-path: themes/casper
  questions:
    theme-path:  Enter theme path
```
NOTE: Option keys seems kinda duplicated

* Proposed options definition:
```
  options:
    theme-path:
      description: 'Theme path'
      default: 'themes/casper'
      question: 'Enter theme path'
      help: 'Extra verbose information'
```
NOTES: 
- description: Displayed when `--help` passed.
- default: used if `--no-interaction` is passed.
- question: Used on interactive mode.
- help: Show if `--learning` option is passed for more information see issue https://github.com/hechoendrupal/DrupalConsole/issues/2303 and PR https://github.com/hechoendrupal/DrupalConsole/pull/2307

## Related issues
- https://github.com/hechoendrupal/DrupalConsole/issues/1898
- https://github.com/hechoendrupal/DrupalConsole/issues/1899
- https://github.com/hechoendrupal/DrupalConsole/pull/2307
