### ISSUE TITLE
[console] Build on config export/import/diff commands to manage sets of config overrides.

### ISSUE THREAD

**Issue by FatherShawn** [hechoendrupal/DrupalConsole#2319]
# Motivation

A typical enterprise site project involves four environments:

- Local dev
- Dev server
- Stage/Testing server
- Production

Teams need to export the base config to a directory as usual, but then also turn off some modules, like views_ui and export the diff. Or imagine you have data coming from a restful service. You want to set the config to hit a dev sandbox in some environments...

# Solution

Configure override directories using yaml:
``` yaml
# base directory is $config_directories[CONFIG_SYNC_DIRECTORY]
override:
  dev:
    directory: config/dev
  prod:
    directory: config/prod
```

And then do something like
``` bash
$ drupal config:import
$ drupal config:import:overrides prod
```
Change some prod specific value and export: 
```
$ drupal config:export:overrides prod
```
