### ISSUE TITLE
[site:mode] prod command should disable cacheability headers

### ISSUE THREAD

**Issue by drubb** [hechoendrupal/DrupalConsole#2322]
When using the site:mode prod command, the following services.yml is created:

```
parameters:
    session.storage.options: { gc_probability: 1, gc_divisor: 100, gc_maxlifetime: 200000, cookie_lifetime: 2000000 }
    twig.config: { debug: false, auto_reload: false, cache: true }
    renderer.config: { required_cache_contexts: ['languages:language_interface', theme, user.permissions], auto_placeholder_conditions: { max-age: 0, contexts: [session, user], tags: {  } } }
    http.response.debug_cacheability_headers: true
    factory.keyvalue: {  }
    factory.keyvalue.expirable: {  }
    filter_protocols: [http, https, ftp, news, nntp, tel, telnet, mailto, irc, ssh, sftp, webcal, rtsp]
```

As you can see, the cacheability headers are enabled, I think they should be disabled (false).
