### ISSUE TITLE
Use single quotes in generated YAML files.

### ISSUE THREAD

**Issue by SchnWalter** [hechoendrupal/DrupalConsole#2759]
Drupal Core uses single quotes for YAML files, I believe that DrupalConsole should follow the same style.

Generate:
```yaml
services:
  coffee.actions_discovery:
    class: Drupal\coffee\CoffeeActionsDiscoveryService
    arguments: ['@module_handler', '@access_manager', '@current_user', '@current_route_match', '@menu.link_tree', '@plugin.manager.menu.link', '@plugin.manager.menu.local_task']
```
Not:
```yaml
services:
  coffee.actions_discovery:
    class: Drupal\coffee\CoffeeActionsDiscoveryService
    arguments: ["@module_handler", "@access_manager", "@current_user", "@current_route_match", "@menu.link_tree", "@plugin.manager.menu.link", "@plugin.manager.menu.local_task"]
```
