### ISSUE TITLE
Chain commands are not working when passing one placeholder and --no-interaction

### ISSUE THREAD

**Issue by marcelovani** [hechoendrupal/DrupalConsole#2964]
I have a custom chain command, which has some default values and a required value.
When I execute the chain with --no-interaction it is complaining about missing placeholders.
example.

chain-db.yml
```
commands:
  - command: site:db
    arguments:
      name: '%{{name}}'
    options:
      db-name: '%{{db-name|drupal}}'
      db-user: '%{{db-user|root}}'
      db-pass: ''
      db-host: '%{{db-port|127.0.0.1}}'
      db-port: '%{{db-port|3306}}'
```
When I run 
`drupal chain --file=chain-db.yml --placeholder="name:site" --no-interaction`
it complains:
> [ERROR] Missing inline placeholder(s) "db-name, db-user, db-port, profile"
> Pass inline placeholders as:
>    --placeholder="db-name:DB-NAME_VALUE"
>    --placeholder="db-user:DB-USER_VALUE"
>    --placeholder="db-port:DB-PORT_VALUE"
>    --placeholder="profile:PROFILE_VALUE"

Ideally it should take name from the provided placeholder and use the default values for the optional parameters
