### ISSUE TITLE
[generate:permission] Missing params and some feedback after the generation

### ISSUE THREAD

**Issue by omero** [hechoendrupal/DrupalConsole#506]
Looking the `generate:permissions`, and comparing with other modules, i see some usefull params.
```yaml
access content:
   title: 'Access Content'
   description: 'Allow access to my content.'
   restrict access: true
```
It will be nice to give some feedback to user, something like; 
```
You can use this permission in the routing file modules/custom/demo/demo.routing.yml example:
node.content:
   requirements:
     _permission: 'access content'
```
I do not think it's necessary ask if you want generate permissions that's the reason to call this command, but we can ask if you want to generate other permission.

Also i note that the command overwrite the permission.yml file, we can make an append, it will be responsability if the user remove the permissions, if they don't use it.
