### ISSUE TITLE
[console] Set defaults for commands on user config file.

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#515]
I am planning to set defaults for commands on that config file at home directory `~/.console/config.yml`, will probably look something like this:

```
command:
  generate:
    module:
      options: 
        module: My example module
        machine-name: example
    controller:
      options: 
        module: example
        class-name: ExampleController
```

The idea is to take advantage of user config file at `~/.console/config.yml` file on user home directory. 

Feature based on this issue at d.o. https://www.drupal.org/node/2392831
