### ISSUE TITLE
[generate:entity:content] The generated entities are not yet fully supported by the views module. 

### ISSUE THREAD

**Issue by vacho** [hechoendrupal/DrupalConsole#552]

**Comment by jmolivas** [comment]
I did a test and it worked this is how do I replicated,
* Create a YAML file to set the commands to automate:
```
# /Users/jmolivas/develop/test-views-integration.yml
commands:
  chain:
    - generate:module
    - generate:entity:content
    - module:install
    - cache:rebuild
  generate:
    module:
      options:
        module: Example module
        machine-name: example
        module-path: /modules/custom/
        description: My example module
        core: 8.x
        package: Test
        controller: false
        dependencies:
        test: false
    entity:
      content:
        options:
          module: example
          entity-class: Foo
          entity-name: foo
  module:
    install:
      arguments:
        module: example
  cache:
    rebuild:
      options:
        cache: all

```
* Execute  `chain` command passing file path
```
$ drupal chain --file=/Users/jmolivas/develop/test-views-integration.yml
```
* Try creating new view from GUI
![screen shot 2015-04-01 at 11 46 55 am](https://cloud.githubusercontent.com/assets/366275/6948839/32eb4cf8-d865-11e4-971d-ef9328485f52.png)

NOTE: This new command is not released yet @vacho you may need to do the steps manually

**Comment by vacho** [comment]
view recognizes entities, but get errors when adding fields in the view query.

**Comment by jmolivas** [comment]
Can you elaborate more, adding error messages or screenshots

**Comment by omero** [comment]
Firstable a update the yml file to use `chain` command

```
commands:
  - command: generate:module
    options:
      module: Example module
      machine-name: example
      module-path: /modules/custom/
      description: My example module
      core: 8.x
      package: Test
      controller: false
      dependencies:
      test: false
  - command: generate:entity:content
    options:
      module: example
      entity-class: Foo
      entity-name: foo
  - command: module:install
    arguments:
      module: example
  - command: cache:rebuild
    options:
      cache: all
```

Secondly, i tried replicate error but everything looks fine
