### ISSUE TITLE
[chain] Not installing module properly

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#639]
When running the `chain` command and the YAML definition contains a `module:install` the module is not properly enabled.

```
commands:
  - command: generate:module
    options:
      module: Example module
      machine-name: example
      module-path: /modules/custom/
      description: My example module
      core: 8.x
      package: Test
      controller: false
      dependencies:
      test: false
  - command: generate:entity:content
    options:
      module: example
      entity-class: Foo
      entity-name: foo
  - command: generate:controller
    options:
      module: example
      class-name: ExampleController
      method-name: index
      route: /example/index
  - command: generate:service
    options:
      module: example
      class-name: ExampleService
      service-name: example.service
      interface: yes
  - command: generate:plugin:block
    options:
      module: example
      class-name: ExampleBlock
      label: Example plugin block
      plugin-id: example_block
  - command: module:install
    arguments:
      module: [example]
  - command: cache:rebuild
    arguments:
      cache: all

```
