### ISSUE TITLE
[generate:entity:config] Doesn't generate menu links

### ISSUE THREAD

**Issue by Crell** [hechoendrupal/DrupalConsole#661]
Per the title, this command generates 8 different files, but it's missing a 9th.  The actual menu link itself.  That means you can't actually GET to the list page for the config entity without manually typing in the URL, which is undesireable.

We should generate the menu links yaml file, too.

**Comment by jmolivas** [comment]
@enzolutions work on this o this PR #687

**Comment by jmolivas** [comment]
@Crell I tested PR #687 by generating  a module and a config entity
![screen shot 2015-06-13 at 11 32 49 pm](https://cloud.githubusercontent.com/assets/366275/8147569/dda8bb36-1225-11e5-891b-b818887d9d4d.png)

This generated a new file: `example.links.menu.yml` with the following content
```
# DefaultEntity menu items definition
entity.default_entity.collection:
  title: 'DefaultEntity'
  route_name: entity.default_entity.collection
  description: 'List DefaultEntity'
  parent: system.admin_structure
```
An new link shown at http://drupal8.dev/admin/structure:
![screen shot 2015-06-13 at 11 46 01 pm](https://cloud.githubusercontent.com/assets/366275/8147575/883c64c6-1226-11e5-9f95-3ee3aea8a61d.png)
