### ISSUE TITLE
Fatal error when using Webprofiler

### ISSUE THREAD

**Issue by mayeco** [hechoendrupal/DrupalConsole#930]
When using the new [Webprofiler](https://www.drupal.org/project/webprofiler) the Drupal Console fail to execute.

    Fatal error: Class 'Drupal\AppConsole\Command\ContainerAwareCommand' not found in /var/www/html/modules/contrib/webprofiler/src/Command/ExportCommand.php on line 22

**Comment by jmolivas** [comment]
I sent a PR  https://github.com/lussoluca/webprofiler/pull/6 to webprofiler fixing the issue, not sure when the new webprofiler will be tagged maybe @lussoluca knows when this will be happening.

**Comment by lussoluca** [comment]
@mayeco you have to use the latest HEAD from webprofiler 8.x-2.x branch. I'll tag a new version later this week.

**Comment by mayeco** [comment]
I was using the HEAD, but now the problem is fixed thank you

**Comment by jmolivas** [comment]
On the next release you will be able to disable custom commands by module, just updating your local config file:
```
# ~/.console/config.yml
application:
...

  disable:
    module:
      - broken_module_name_one
      - broken_module_name_two
```
