### ISSUE TITLE
[translation] Improve translations management

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#942]
# Improve translations management
### Actual situation
Actually all of the commands translations are located at `config/translations/` one big file for each language, this make it complicated to manage, add, delete, update.

```
config/translations/

├── console.en.yml
├── console.es.yml
├── console.fr.yml
├── console.hu.yml
├── console.pt.yml
├── console.ro.yml
├── console.vn.yml
└── console.zh.yml
```
For a better idea how the content looks lie, you can take a look at the complete file content at [config/translations/console.en.yml](https://github.com/hechoendrupal/DrupalConsole/blob/master/config/translations/console.en.yml)

### Initial proposal for improving translations management.
After discussing with the other maintainers of the project we came with this idea.
### Create a new directory for each language
```
config/translations/
├── en
└── es
```
### Separate each command translations into a separated file
```
config/translations/
├── en
│   └── generate.comand.yml
└── es
    └── generate.comand.yml
```
### Single command file content
```
description: Generate commands for the console.
help: The <info>generate:command</info> command helps you generate a new command.
welcome: Welcome to the Drupal Command generator
options:
  module: common.options.module
  controller-title: 'Controller title'
  class-name: Command Class name
  command: Command name (Must end with the word 'Commmand')
  container: Access the services container
questions:
  module: common.questions.module
  class-name: Enter the Command Class name
  command: Enter the Command name
  container: Do you need to access the service container
messages:
  title-not-empty: 'Title cannot be empty'
```
#### Pros:
* Easy to navigate and manage.
* No need to specify the nested levels, all of the translation are within the scope of the command.
* Less merge conflicts.

#### Cons:
* Too many files.
* Need to create a new command to merge command translations back in one big file, before deploying and tagging a release.
